keybindings:
  # When F is pressed
  f:
    # Permission needed to use this keybinding. Leave empty for no permission.
    permission: permission
    # Whether this keybinding should be enabled (true|false)
    enabled: true
    cancel-event: true
    cooldown: 10
    commands:
      - say [f] first command
      - say [f] second command

  # When Q is pressed
  q:
    # Permission needed to use this keybinding. Leave empty for no permission.
    permission: permission
    # Whether this keybinding should be enabled (true|false)
    enabled: true
    cancel-event: true
    cooldown: 10
    commands:
      - say [q] first command
      - say [q] second command

  # When SHIFT + F is pressed
  shift-f:
    # Permission needed to use this keybinding. Leave empty for no permission.
    permission: permission
    # Whether this keybinding should be enabled (true|false)
    enabled: true
    cancel-event: true
    cooldown: 10
    commands:
      - say [shift-f] first command
      - say [shift-f] second command

  # When SHIFT + Q is pressed
  shift-q:
    # Permission needed to use this keybinding. Leave empty for no permission.
    permission: permission
    # Whether this keybinding should be enabled (true|false)
    enabled: true
    cancel-event: true
    cooldown: 10
    commands:
      - say [shift-q] first command
      - say [shift-q] second command